name: 'Compatibility Checks'
on:
  push:
    branches:
      - dev
      - release
  pull_request_target:

jobs:
  check:
    name: Check Compatibility for Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.9-dev', '3.10-dev']
        os: ['ubuntu-latest', 'macos-latest']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          python -m pip install --upgrade pip 
          pip install --upgrade wheel
          pip install .
          pip install -r compatibility.txt
      - name: Show python version and show package
        run: |
          python --version
          sopel --version
          pip show MirahezeBot-Plugins
      - name: Check compatibility
        run: |
          pip check
      - name: Run pip freeze and pipdeptree
        run: |
          pip freeze
          pipdeptree
