name: 'Create Debian Packages'
on:
  push:
    branches:
      - dev
      - release
  pull_request:

jobs:
  test:
    name: Test Build (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10-dev']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          python -m pip install --upgrade pip make-deb
          sudo apt install dh-virtualenv
          pip install -r dev-requirements.txt
      - name: Show python version and show package
        run: |
          python --version
          pip --version
      - name: Create package
        run: |
          make-deb
          dpkg-buildpackage -us -uc
