name: 'Create Debian Packages'
on:
  push:
    branches:
      - dev
      - release
  pull_request:

jobs:
  test:
    name: Test Build (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          sudo apt install debhelper dh-virtualenv python3-setuptools
          pip install -r dev-requirements.txt
          pyproject-build --wheel --outdir dist .
          find dist -name "*.whl" | xargs pip3 install
      - name: Show python version and show package
        run: |
          python --version
          pip --version
      - name: Create package
        run: |
          dpkg-buildpackage -us -uc
      - name: List installed packages (I)
        run: pip freeze
      - name: Reset pip
        run: |
          pip uninstall -y MirahezeBot-Plugins
          pip freeze | xargs pip uninstall -y
      - name: List installed packages (II)
        run: pip freeze
      - name: where is the deb
        run: find / -name "mirahezebot-plugins_9.1.0_*.deb"
        
